[project]
name = "pn-trajectories-26"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astroquery>=0.4.11",
    "jupyter>=1.1.1",
    "lab>=8.9",
    "numpy>=2.4.6",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
